create database customer_behaviours;

use customer_behaviours;

SELECT * FROM my_customer_table;

---What is the total revenue generated by male vs female

select gender,SUM(purchase_amount) as revenue
from my_customer_table
group by gender;

---Which customer used a discount but still spent more than average purchase amount

select customer_id,purchase_amount 
from my_customer_table
where discount_applied = 'yes' and 
purchase_amount >= (select AVG(purchase_amount) from my_Customer_table)

----Which is the top 5 products with the highest average review rating 

select item_purchased,ROUND(avg(cast(review_rating as float)),2) as average_product_rating
from my_customer_table
group by item_purchased
order by avg(review_rating) desc;

---Compare the average purchase amounts between standard and express shipping

select shipping_type,
round(avg(cast(purchase_amount as float)),2) from my_customer_table
where shipping_type in ('Standard','Express')
group by shipping_type;

--- Do subscribed customers spend more compare average spend and total revenue between subscribers and non-subscribers

select subscription_status,
count(customer_id) as total_customers,
round(avg(cast(purchase_amount as float)),2) as avg_spend,
round(sum(cast(purchase_amount as float)),2) as total_revenue
from my_customer_table
group by subscription_status
order by total_revenue,avg_spend desc;

---Which 5 products have the highest percentage of purchases with discounts applied

select top 5 item_purchased,
round(100 * sum(case when discount_applied ='yes' then 1 else 0 end)/ count(*),2) as discount_rate
from my_customer_table
group by item_purchased
order by discount_rate desc ;

----segment customers into new, returnning and loyal based on their total number of previous purchase and slow the count of each segment

with customer_type as (
Select customer_id,
       previous_purchases,
case 
    when previous_purchases = 1 then 'New'
	when previous_purchases between 2 AND 10 then 'Returning'
	ELSE 'Loyal'
END As customer_segment
from my_customer_table
)

Select customer_segment, count(*) AS 'number of customer'
from customer_type 
group by customer_segment;

---- what are the top 3 most purchased product with in each category

with item_counts as(
select category,
       item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() OVER(partition by category 
                  order by count(customer_id) DESC) AS item_rank
from my_customer_table
group by category ,
         item_purchased)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank <=3;

---Are customers who are repeat buyers (more than 5 previous porchases )also likly to subscriber ?

Select subscription_status,
count(customer_id) as repet_buyers
from my_customer_table
where previous_purchases > 5
group by subscription_status ;

---What is the revenue contribution of each age group?

select age_group,
sum(purchase_amount) as total_revenue
from my_customer_table
group by age_group
order by total_revenue desc ;






